<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LD-4V2P3G2" name="Default test" tests="9" failures="1" timestamp="21 Mar 2018 22:44:23 GMT" time="148.257" errors="0">
  <testcase name="testVerifyLeadTheWayLink_1455q" time="17.025" classname="com.rf.test.website.LSD.LSDLinkTests">
    <failure type="java.lang.AssertionError" message="1.Current URL : https://sfm-prd-okt-w01.rf.local/IWA/ does not contains randfjourney
">
      <![CDATA[java.lang.AssertionError: 1.Current URL : https://sfm-prd-okt-w01.rf.local/IWA/ does not contains randfjourney

	at com.rf.core.utils.SoftAssert.assertAll(SoftAssert.java:56)
	at com.rf.test.website.LSD.LSDLinkTests.testVerifyLeadTheWayLink_1455q(LSDLinkTests.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testVerifyLeadTheWayLink_1455q -->
  <testcase name="testVerifyRFConnectionLink_1456q" time="6.393" classname="com.rf.test.website.LSD.LSDLinkTests"/>
  <testcase name="testVerifyRFJourneyLink_1457q" time="6.376" classname="com.rf.test.website.LSD.LSDLinkTests"/>
  <testcase name="testVerifyRFMallLink_1458q" time="6.316" classname="com.rf.test.website.LSD.LSDLinkTests"/>
  <testcase name="testVerifyRFPaydayLink_1459q" time="6.276" classname="com.rf.test.website.LSD.LSDLinkTests"/>
  <testcase name="testVerifyLinkCommsCorner_1447q" time="6.274" classname="com.rf.test.website.LSD.LSDLinkTests"/>
  <testcase name="testVerifyLinkConsultantLEDEvents_1448" time="6.814" classname="com.rf.test.website.LSD.LSDLinkTests"/>
  <testcase name="testVerifyLinkCorporateEvents_1449q" time="10.477" classname="com.rf.test.website.LSD.LSDLinkTests"/>
  <testcase name="testVerifyLinkGettingStarted_1450q" time="6.296" classname="com.rf.test.website.LSD.LSDLinkTests"/>
</testsuite> <!-- Default test -->
