<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LD-4V2P3G2" name="Default test" tests="1" failures="0" timestamp="3 Apr 2018 00:48:53 GMT" time="0.191" errors="0">
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.rf.test.website.storeFront.heirloom.CorpTest">
    <failure type="org.openqa.selenium.WebDriverException" message="MobileLabs.AirStream.Protocol.AirStreamPeerException: Object reference not set to an instance of an object
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Gateway.Protocol.IAppiumResponse].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Gateway.Protocol.AppiumProxyServiceHttpAdapter+&amp;lt;Request&amp;gt;d__4.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[System.Byte[]].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Framework.Async.IO.AppiumClient+&amp;lt;RequestUninitialized&amp;gt;d__27.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[System.String].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Framework.Async.IO.AppiumClient+&amp;lt;RequestUninitialized&amp;gt;d__29`1[MobileLabs.AirStream.Framework.Async.IO.AppiumResponse`1[System.Collections.Generic.Dictionary`2[System.String,System.Object]]].MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Framework.Async.IO.AppiumResponse`1[System.Collections.Generic.Dictionary`2[System.String,System.Object]]].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Framework.Async.IO.AppiumClient+&amp;lt;InitializeAsync&amp;gt;d__21.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter.cs:60 
  at MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession+&amp;lt;StartAppiumSession&amp;gt;d__107.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Gateway.Protocol.AppiumStartServiceResult].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession+&amp;lt;Initialize&amp;gt;d__92.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter.cs:60 
  at MobileLabs.AirStream.Framework.Async.IO.AppiumClient+&amp;lt;Request&amp;gt;d__24`1[MobileLabs.AirStream.Framework.Async.IO.AppiumResponse`1[System.Object]].MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession+&amp;lt;Initialize&amp;gt;d__92.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter.cs:60 
  at MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession+&amp;lt;Create&amp;gt;d__90.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Web.Controllers.AppiumController+&amp;lt;CreateSession&amp;gt;d__13.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Framework.IO.Mvc.MvcJsonResult].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Web.Controllers.AppiumController+&amp;lt;HandleRequestAsync&amp;gt;d__10.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
Fault information: System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089: Object reference not set to an instance of an object
  at MobileLabs.DeviceConnect.Services.Gateway.AppiumController+&amp;lt;RequestCore&amp;gt;d__85.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Gateway.Protocol.IAppiumResponse].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.DeviceConnect.Services.Gateway.AppiumController+&amp;lt;Request&amp;gt;d__84.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Gateway.Protocol.IAppiumResponse].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.DeviceConnect.Services.Gateway.AirStreamGatewayService+&amp;lt;AppiumPerformRequest&amp;gt;d__132.MoveNext () [0x00000] in &amp;lt;filename unknown&amp;gt;:0 

 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 16.09 seconds
Build info: version: &amp;apos;3.7.1&amp;apos;, revision: &amp;apos;8a0099a&amp;apos;, time: &amp;apos;2017-11-06T21:01:39.354Z&amp;apos;
System info: host: &amp;apos;LD-4V2P3G2&amp;apos;, ip: &amp;apos;10.6.64.221&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_161&amp;apos;
Driver info: driver.version: RFWebsiteDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: MobileLabs.AirStream.Protocol.AirStreamPeerException: Object reference not set to an instance of an object
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Gateway.Protocol.IAppiumResponse].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Gateway.Protocol.AppiumProxyServiceHttpAdapter+<Request>d__4.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[System.Byte[]].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Framework.Async.IO.AppiumClient+<RequestUninitialized>d__27.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[System.String].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Framework.Async.IO.AppiumClient+<RequestUninitialized>d__29`1[MobileLabs.AirStream.Framework.Async.IO.AppiumResponse`1[System.Collections.Generic.Dictionary`2[System.String,System.Object]]].MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Framework.Async.IO.AppiumResponse`1[System.Collections.Generic.Dictionary`2[System.String,System.Object]]].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Framework.Async.IO.AppiumClient+<InitializeAsync>d__21.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter.cs:60 
  at MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession+<StartAppiumSession>d__107.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Gateway.Protocol.AppiumStartServiceResult].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession+<Initialize>d__92.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter.cs:60 
  at MobileLabs.AirStream.Framework.Async.IO.AppiumClient+<Request>d__24`1[MobileLabs.AirStream.Framework.Async.IO.AppiumResponse`1[System.Object]].MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession+<Initialize>d__92.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter.cs:60 
  at MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession+<Create>d__90.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Framework.Async.IO.Appium.AppiumSession].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Web.Controllers.AppiumController+<CreateSession>d__13.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Framework.IO.Mvc.MvcJsonResult].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.AirStream.Web.Controllers.AppiumController+<HandleRequestAsync>d__10.MoveNext () [0x00000] in <filename unknown>:0 
Fault information: System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089: Object reference not set to an instance of an object
  at MobileLabs.DeviceConnect.Services.Gateway.AppiumController+<RequestCore>d__85.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Gateway.Protocol.IAppiumResponse].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.DeviceConnect.Services.Gateway.AppiumController+<Request>d__84.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62 
  at System.Runtime.CompilerServices.TaskAwaiter`1[MobileLabs.AirStream.Gateway.Protocol.IAppiumResponse].GetResult () [0x00034] in /Users/eiz/code/mono/mcs/class/corlib/System.Runtime.CompilerServices/TaskAwaiter_T.cs:59 
  at MobileLabs.DeviceConnect.Services.Gateway.AirStreamGatewayService+<AppiumPerformRequest>d__132.MoveNext () [0x00000] in <filename unknown>:0 

 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 16.09 seconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'LD-4V2P3G2', ip: '10.6.64.221', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: RFWebsiteDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:83)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:93)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:78)
	at com.rf.core.driver.website.RFWebsiteDriver.loadApplication(RFWebsiteDriver.java:122)
	at com.rf.test.website.RFHeirloomWebsiteBaseTest.setUp(RFHeirloomWebsiteBaseTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@BeforeClass beforeClass" time="0.0" classname="com.rf.test.website.storeFront.heirloom.CorpTest">
    <skipped/>
  </testcase> <!-- @BeforeClass beforeClass -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rf.test.website.storeFront.heirloom.CorpTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod tearDownAfterMethod" time="0.0" classname="com.rf.test.website.storeFront.heirloom.CorpTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDownAfterMethod -->
  <testcase name="testConsultantExpressEnrollment_505" time="0.053" classname="com.rf.test.website.storeFront.heirloom.CorpTest">
    <skipped/>
  </testcase> <!-- testConsultantExpressEnrollment_505 -->
</testsuite> <!-- Default test -->
