{"uuid":"d2290a4f-72ff-49a3-9240-34c299dcf745","historyId":"ec670cbf9092af1bfb6b5a053f09243b","fullName":"com.rf.test.website.LSD.LSDCustomerTests.testTotalNumberOfPCsThisMonth_3013q","labels":[{"name":"package","value":"com.rf.test.website.LSD.LSDCustomerTests"},{"name":"testClass","value":"com.rf.test.website.LSD.LSDCustomerTests"},{"name":"testMethod","value":"testTotalNumberOfPCsThisMonth_3013q"},{"name":"parentSuite","value":"pulseRegressionSuite"},{"name":"suite","value":"pulseRegressionTest"},{"name":"subSuite","value":"com.rf.test.website.LSD.LSDCustomerTests"},{"name":"host","value":"LD-4V2P3G2"},{"name":"thread","value":"19412@LD-4V2P3G2.main(1)"}],"links":[],"name":"testTotalNumberOfPCsThisMonth_3013q","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Could not get JDBC Connection; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host 10.3.0.218, port 1433 has failed. Error: \"connect timed out. Verify the connection properties, check that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port, and that no firewall is blocking TCP connections to the port.\".","trace":"org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host 10.3.0.218, port 1433 has failed. Error: \"connect timed out. Verify the connection properties, check that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port, and that no firewall is blocking TCP connections to the port.\".\r\nCaused by: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host 10.3.0.218, port 1433 has failed. Error: \"connect timed out. Verify the connection properties, check that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port, and that no firewall is blocking TCP connections to the port.\".\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:170)\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1049)\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:833)\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:716)\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:841)\r\n\tat java.sql.DriverManager.getConnection(Unknown Source)\r\n\tat java.sql.DriverManager.getConnection(Unknown Source)\r\n\tat org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:291)\r\n\tat org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:277)\r\n\tat org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:259)\r\n\tat org.springframework.jdbc.datasource.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:240)\r\n\tat org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:113)\r\n\tat org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)\r\n\tat org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:328)\r\n\tat org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:404)\r\n\tat org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:412)\r\n\tat com.rf.core.utils.DBUtil.performDatabaseQuery(DBUtil.java:80)\r\n\tat com.rf.test.website.LSD.LSDCustomerTests.testTotalNumberOfPCsThisMonth_3013q(LSDCustomerTests.java:25)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n\tat org.testng.internal.Invoker.retryFailed(Invoker.java:1049)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n\tat org.testng.TestRunner.run(TestRunner.java:617)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:348)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:254)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n\tat org.testng.TestNG.run(TestNG.java:1057)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n"},"stage":"finished","start":1519870484829,"stop":1519870514432,"parameters":[]}