<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LD-4V2P3G2" name="Default test" tests="4" failures="1" timestamp="22 Mar 2018 06:14:30 GMT" time="72.502" errors="0">
  <testcase name="testVerifyLeadTheWayLink_1455q" time="9.869" classname="com.rf.test.website.LSD.LSDLinkTests">
    <failure type="java.lang.AssertionError" message="1.Current URL : https://safe.menlosecurity.com/safeview-auth-server/saml does not contains randfjourney
">
      <![CDATA[java.lang.AssertionError: 1.Current URL : https://safe.menlosecurity.com/safeview-auth-server/saml does not contains randfjourney

	at com.rf.core.utils.SoftAssert.assertAll(SoftAssert.java:56)
	at com.rf.test.website.LSD.LSDLinkTests.testVerifyLeadTheWayLink_1455q(LSDLinkTests.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testVerifyLeadTheWayLink_1455q -->
  <testcase name="testVerifyRFConnectionLink_1456q" time="7.971" classname="com.rf.test.website.LSD.LSDLinkTests"/>
  <testcase name="testVerifyRFJourneyLink_1457q" time="6.389" classname="com.rf.test.website.LSD.LSDLinkTests"/>
  <testcase name="testVerifyLinkGettingStarted_1450q" time="6.282" classname="com.rf.test.website.LSD.LSDLinkTests"/>
</testsuite> <!-- Default test -->
